Sources/DatadogSDKTesting/DDEnvironmentValues.swift
Sources/DatadogSDKTesting/DDTracer.swift
Tests/DatadogSDKTesting/DDEnvironmentValuesTests.swift

Use repository name as default test service name
If the user has not set `DD_SERVICE`, use first the repository name recovered from git and only process name as last resource

Use repository name as default test service name

---

README.md
Sources/DatadogSDKTesting/DDEnvironmentValues.swift
Sources/DatadogSDKTesting/FrameworkLoadHandler.swift
Sources/DatadogSDKTesting/Utils/XCUIApplicationSwizzler.swift
Tests/DatadogSDKTesting/CISpec.swift
Tests/DatadogSDKTesting/DDEnvironmentValuesTests.swift
Tests/DatadogSDKTesting/FrameworkLoadHandlerTests.swift

Allow configuration values to be provided in the Info.plist files of the test bundles apart from the environment variables of the test action. If values appear both in environment variables and plist file, environment value takes precedence.
Relates to #40
When recovering the environment values we use the infoDictionary of the test bundle as a fallback if the environment variable doesn't exist. 

CIAPP-2526 Manual test support

---

DatadogSDKTesting.xcodeproj/project.pbxproj
Sources/DatadogSDKTesting/DDTracer.swift
Tests/DatadogSDKTesting/DDTracerTests.swift

Update to Event Platform Intake API v2
Linking with latest opentelemetry-swift which supports V2 and changing the endpoints in the tests
- [ X ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ X ] Make sure each commit and the PR mention the Issue number or JIRA reference

CIAPP-2480  Update to Event Platform Intake API v2

---

DatadogSDKTesting.xcodeproj/project.pbxproj

Add support for async/await methods and tests
With the current implementation of Async/Await and structured concurrency, otel version used for automatic context handling was not working, and some changes were needed. async/await methods and network calling were not inheriting the parent span, so were not associated to the test span.
Update to otel-swift version supporting async/await

CIAPP-2670 - Support-active-context-with-structured-concurrency

---

Sources/DatadogSDKTesting/DDTags.swift
Sources/DatadogSDKTesting/DDTestObserver.swift
Sources/DatadogSDKTesting/Utils/XCUIApplicationSwizzler.swift

Identify UITests from standard unit tests
@iGranDav told me that it would be useful for them to have an easy way to identify UI tests form the rest.
Add a special tag for identifying UITests that is automatically set when XCUIApplication is launched

CIAPP-2617 - Identify UITests from standard unit tests

---

Sources/DatadogSDKTesting/DDTags.swift
Sources/DatadogSDKTesting/DDTestObserver.swift
Sources/DatadogSDKTesting/DDTracer.swift

Report tracer language and version as the specification now implies under the tracer tag, it allows reporting the version of the application under testing
`tracer.language` and `tracer.version` now have the information that will be used in the future for all tracers

CIAPP-2724 Add testing framework version

---

Sources/DatadogSDKTesting/DDTags.swift
Sources/DatadogSDKTesting/DDTestObserver.swift
Sources/DatadogSDKTesting/DDTracer.swift
Tests/DatadogSDKTesting/DDTestObserverTests.swift

Xcode 13 added support for new benchmark types like memory, cpu and more. Overhaul all benchmarking tags to support any of the possible benchmarks that Xcode supports.
Parse any possible benchmark value that Xcode returns and use the new benchmark format to report them

CIAPP-2667 Add support for new benchmark values in XCTest

---

DatadogSDKTesting.xcodeproj/project.pbxproj
LICENSE-3rdparty.csv
Sources/DatadogSDKTesting/DDTracer.swift
Sources/DatadogSDKTesting/DatadogSDKTesting.h
Sources/DatadogSDKTesting/Objc/NTPKit/LICENSE
Sources/DatadogSDKTesting/Objc/NTPKit/NTPServer.h
Sources/DatadogSDKTesting/Objc/NTPKit/NTPServer.m
Sources/DatadogSDKTesting/Objc/NTPKit/NTPTypes.c
Sources/DatadogSDKTesting/Objc/NTPKit/NTPTypes.h
Sources/DatadogSDKTesting/Utils/NTPClock.swift

Reenabled NTP clock functionality, since previous implementation was removed after returning some invalid values. 
Changed from Kronos to good-old NTPKit that we only use to recover the time offset. We are providing NTPKit here because it does not support SPM and is not going to change

CIAPP-3060 Reenable NTP clock

---

Sources/DatadogSDKTesting/DDTags.swift
Sources/DatadogSDKTesting/DDTestMonitor.swift
Sources/DatadogSDKTesting/DDTestSession.swift
Sources/DatadogSDKTesting/Utils/PlatformUtils.swift
Sources/DatadogSDKTesting/Utils/XCUIApplicationSwizzler.swift

Reports UI setting of tests running: appearance, localization and orientation (only with iOS).
Xcode 13 has a setting for running tests  `runsForEachTargetApplicationUIConfiguration`, this allow the user to run the test just changing these values. 
With the previous code a change in just the orientation of the device of the app would be treated as a retry, and a failure would be marked as flaky, but we really want to fail the test if it fails because of the change of one of these setting. The tags that we are reporting here will also be treated as a configuration tag by the backend, so will be differentiated from the same test running with other settings ( like a test failing in iOS 12 but not on iOS 14 is marked as a failure and not a flaky)
These settings are only reported on UI tests, …

Report UI settings

---

DatadogSDKTesting.xcodeproj/project.pbxproj
Sources/DatadogSDKTesting/Crashes/DDSymbolicator.swift
Sources/DatadogSDKTesting/DDEnvironmentValues.swift
Sources/DatadogSDKTesting/DDTags.swift
Sources/DatadogSDKTesting/NetworkInstrumentation/DDNetworkInstrumentation.swift
Sources/DatadogSDKTesting/Utils/SwiftExtensions.swift
Tests/DatadogSDKTesting/Crashes/DDSymbolicatorTests.swift

Add `call_stack` to all network requests by default, it allows knowing what is the origin of any network request so the developer can know how it get there. It partially symbolicates the output and it has an option to fully symbolicate it, but is quite time consuming and must be enabled explicitly
It adds the `call_stack` tag to all network requests that are created in the app, removing the lines related to our own insrumentation and only showing user code at the top. It also includes two new environment variables to control the feature:
- DD_DISABLE_NETWORK_CALL_STACK to disable the functionality
- DD_ENABLE_NETWORK_CALL_STACK_SYMBOLICATED to enable full symbolication 
Fully symbolication can only be achievable when running on iOS simulator or macOS, and must be activated explicitly …

Add call stack to all network requests by default

---

DatadogSDKTesting.xcodeproj/project.pbxproj
Sources/DatadogSDKTesting/Crashes/DDCrashes.swift
Sources/DatadogSDKTesting/DDEnvironmentValues.swift
Sources/DatadogSDKTesting/DDTestModule.swift
Sources/DatadogSDKTesting/Objc/LibraryInitializer.m
Sources/DatadogSDKTesting/Objc/SanitizerMessageHandler.m
Sources/DatadogSDKTesting/Utils/SanitizerHelper.swift

Add support for reporting sanitizer errors
Add a handler that is called by sanitizers when printing errors to save those messages in the library 
If there is any sanitizer message fail the module and show the error associated to it, it cannot be associated to the test because the sanitizer check runs asynchronously
Save this information in a file along the crash log so it can be recovered after it crashes in a CI environment

CIAPP - 4802 - Add support for reporting sanitizer errors

---

DatadogSDKTesting.xcodeproj/project.pbxproj
Sources/EventsExporter/EventsExporter.swift
Sources/EventsExporter/Logs/LogEncoder.swift

Update the code to build with the latest opentelemetry-swift. The build was failing because `SpanExporter` added a new timeout parameter in 1.7.0. This PR changes the signature of the function so it builds, but doesn't actually use the new parameter.

Update to opentelemetry-swift 1.7.0

---

Scripts/uploadBinary.sh

I missed the `HEAD:main` bit in https://github.com/DataDog/dd-sdk-swift-testing/pull/85, so the script fails again in https://github.com/DataDog/dd-sdk-swift-testing/actions/runs/7194920950/job/19596489937

Fix upload script again 

---

Package@swift-5.3.swift

Generated automatically in https://github.com/DataDog/dd-sdk-swift-testing/actions/runs/7195300085/job/19597656467 as part of release https://github.com/DataDog/dd-sdk-swift-testing/releases/tag/2.4.0

Updated binary package version to 2.4.0

---

Sources/DatadogSDKTesting/DDTags.swift
Sources/DatadogSDKTesting/DDTest.swift
Sources/DatadogSDKTesting/DDTestObserver.swift
Sources/DatadogSDKTesting/Environment/Environment.swift
Sources/DatadogSDKTesting/Utils/SwiftExtensions.swift
Sources/EventsExporter/Spans/SpanEncoder.swift
Tests/DatadogSDKTesting/DDTestObserverTests.swift
Tests/DatadogSDKTesting/FrameworkLoadHandlerTests.swift

Added sending of skipped tests to the backend. Fixed span serialisation
* Added skipped tests sending
* Cleaned XCTObserver state management
* Fixed span serialisation

[CIVIS-9212] send tests skipped by ITR to the backend

---

Sources/DatadogSDKTesting/Config.swift
Sources/DatadogSDKTesting/DDTestMonitor.swift
Sources/DatadogSDKTesting/DDTracer.swift
Sources/DatadogSDKTesting/Environment/EnvironmentKeys.swift
Sources/DatadogSDKTesting/Utils/XCUIApplicationSwizzler.swift
Tests/DatadogSDKTesting/DDTracerTests.swift

Allows two testing processes to run on the same machine at the same time.
* Changed Mach Port name to unique generated one.
* Added port name UUID to the child process environment.

[CIVIS-9813] implemented channel name fix

---

.github/CODEOWNERS
IntegrationTests/UITests/IntegrationTestsUITests.xctestplan
Sources/DatadogSDKTesting/Config.swift
Sources/DatadogSDKTesting/DDTestMonitor.swift
Sources/DatadogSDKTesting/DDTracer.swift
Sources/DatadogSDKTesting/Environment/EnvironmentKeys.swift
Sources/DatadogSDKTesting/Utils/Clock.swift
Sources/EventsExporter/CoverageExporter/CoverageExporter.swift
Sources/EventsExporter/ExporterConfiguration.swift
Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
Sources/EventsExporter/Upload/HTTPHeader.swift
Tests/EventsExporter/EventsExporterTests.swift
Tests/EventsExporter/Logs/LogsExporterTests.swift
Tests/EventsExporter/Spans/SpansExporterTests.swift

Removed Application Key requirement for ITR
Removed environment variable and HTTP headers

[CIVIS-2859] Remove application key requirement for ITR

---

Makefile

gh login isn't needed for GH_TOKEN
Removed gh login call

removed gh login from the release script

---

.github/workflows/createRelease.yml
DatadogSDKTesting.podspec
Makefile

Podspec should be pushed to the central repository for release.
Added step to makefile for publishing and env secret with token

push pod to the repository on release

---

DatadogSDKTesting.xcodeproj/project.pbxproj
LICENSE-3rdparty.csv
Sources/DatadogSDKTesting/Config.swift
Sources/DatadogSDKTesting/Coverage/DDCoverageHelper.swift
Sources/DatadogSDKTesting/DDTestMonitor.swift
Sources/DatadogSDKTesting/DDTracer.swift
Sources/DatadogSDKTesting/Environment/EnvironmentKeys.swift
Sources/DatadogSDKTesting/ImageSymbols/DDSymbolicator.swift
Sources/EventsExporter/CoverageExporter/CoverageExporter.swift
Sources/EventsExporter/ExporterConfiguration.swift
Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
Sources/EventsExporter/Logs/LogsExporter.swift
Sources/EventsExporter/Spans/SpansExporter.swift
Sources/EventsExporter/Upload/HTTPClient.swift
Tests/EventsExporter/EventsExporterTests.swift
Tests/EventsExporter/Logs/LogsExporterTests.swift
Tests/EventsExporter/Spans/SpansExporterTests.swift

Test Code Coverage should be dumped for debugging only when it's needed, not in a general debug mode.
Added special env variable to enable test coverage debug. Save files only when explicitly enabled

added env variable for ITR debug

---

IntegrationTests/UITests/IntegrationTestsUITests.xctestplan
Sources/DatadogSDKTesting/Utils/GitInfo.swift

Git parser should save tag into branch info if there are no branches in the FETCH_HEAD file
Set branch if there is a branch or set first value for the commit. 

fallback if fetch_head doesn't have branch

---

Sources/DatadogSDKTesting/Coverage/DDCoverageHelper.swift
Sources/EventsExporter/CoverageExporter/CoverageExporter.swift
Sources/EventsExporter/Utils/Spawn.swift

Test process crashes because open file limit is too small by default
Called `setrlimit` method when Code Coverage is enabled to increase open file limit

increase amount of open files for code coverage

---

.github/workflows/createRelease.yml

Added permissions to the job so I can remove global token write permissions.
Updated workflow file with permissions property

[VULN-8074] added GH token write permissions for the release job

---

DatadogSDKTesting.xcodeproj/project.pbxproj
Sources/DatadogSDKTesting/Config.swift
Sources/DatadogSDKTesting/Coverage/CoverageSettings.swift
Sources/DatadogSDKTesting/Coverage/DDCoverageHelper.swift
Sources/DatadogSDKTesting/DDTestModule.swift
Sources/DatadogSDKTesting/DDTestMonitor.swift
Sources/DatadogSDKTesting/Environment/EnvironmentKeys.swift
Sources/DatadogSDKTesting/FrameworkLoadHandler.swift

Added a special mode for Code Coverage which can be enabled with env variable. It breaks total code coverage, but should work as workaround for cases when total coverage file grows too big
Added configuration parameter end environment variable. If total mode is disabled disable backwriting to the total file.

Added special per-test only mode for code coverage

---

.github/workflows/createRelease.yml
Makefile
RELEASEMANAGEMENT.md

Current release process recreates release tag after xcframework build. This leads to cache and build problems on the users CI. Fixed this behaviour.
Release is done through workflow call. It will create tag and draft release automatically after the build

[SDTEST-1351] creating tag and release after build to avoid errors
