- Sources/DatadogSDKTesting/DDEnvironmentValues.swift
Add commit message and authors to some CI that were missing
Read more environment variables
> CIAPP-2052 Add rich commit metadata from envvars to some CI providers

- Sources/DatadogSDKTesting/Utils/CodeOwners.swift
- Tests/DatadogSDKTesting/Utils/CodeOwnersTests.swift
Add support for git lab sections in Codeowners
Handle sections also in the parser
> CIAPP - 3896 add support for gitlab sections in Codeowners

- Sources/DatadogSDKTesting/DDEnvironmentValues.swift
- Tests/fixtures/ci/awscodepipeline.json
Add code to extract env vars & spec test.
> Add support for AWS CodePipeline

- Scripts/uploadBinary.sh
We don't allow direct pushes to main anymore: https://github.com/DataDog/dd-sdk-swift-testing/actions/runs/7194533047/job/19595257635
Create a separate branch that can be reviewed.
> Update uploadBinary script

- .github/workflows/codeQL.yml
- .github/workflows/createRelease.yml
- .github/workflows/integrationTests.yml
- Makefile
Quick Fix: fixed CI configs so CodeQL and Integration Tests actions work
* Removed xcbeautify update. It fails on old macOS.
* Updated CodeQL actions.
> updates for CI

- DatadogSDKTesting.xcodeproj/project.pbxproj
- Package.swift
- Sources/DatadogSDKTesting/Coverage/DDCoverageHelper.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/DDTracer.swift
- Sources/DatadogSDKTesting/Environment/Environment.swift
- Sources/DatadogSDKTesting/FrameworkLoadHandler.swift
- Sources/DatadogSDKTesting/ImageSymbols/DDSymbolicator.swift
- Sources/DatadogSDKTesting/IntelligentTestRunner/GitUploader.swift
- Sources/DatadogSDKTesting/Utils/Log.swift
- Sources/EventsExporter/CoverageExporter/CoverageExporter.swift
- Sources/EventsExporter/CoverageExporter/DDCoverageConversor.swift
- Sources/EventsExporter/EventsExporter.swift
- Sources/EventsExporter/ExporterConfiguration.swift
- Sources/EventsExporter/Files/Directory.swift
- Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
- Sources/EventsExporter/Utils/Log.swift
- Sources/EventsExporter/Utils/Spawn.swift
- Tests/EventsExporter/EventsExporterTests.swift
- Tests/EventsExporter/Helpers/Logger.swift
- Tests/EventsExporter/Helpers/TestsDirectory.swift
- Tests/EventsExporter/Logs/LogsExporterTests.swift
- Tests/EventsExporter/Spans/SpansExporterTests.swift
- Tests/EventsExporter/Utils/SpawnTests.swift
Fixed URL loading for Git
* Split subprocess error and output streams for Spawn.
* Better error handling for subprocesses.
* Better logs for debugging.
> [CIVIS-9740] Swift library sends bad Git URL

- Package.swift
- Sources/CDatadogSDKTesting/include/SubprocessSpawn.h
- Sources/CDatadogSDKTesting/include/SubprocessWait.h
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/IntelligentTestRunner/GitUploader.swift
- Sources/DatadogSDKTesting/IntelligentTestRunner/IntelligentTestRunner.swift
- Sources/EventsExporter/Files/Directory.swift
- Sources/EventsExporter/Files/File.swift
- Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
Updated git unshallow process to the latest specs
* Updated commands to the latest specs
* Fixed logic
> [CIVIS-9214] Improve git unshallow

- Package.swift
- Sources/DatadogSDKTesting/DDTags.swift
- Sources/DatadogSDKTesting/DDTest.swift
- Sources/DatadogSDKTesting/IntelligentTestRunner/IntelligentTestRunner.swift
- Sources/EventsExporter/EventsExporter.swift
- Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
- Sources/EventsExporter/IntelligentTestRunner/SkipTestsFormat.swift
- Tests/EventsExporter/Files/DirectoryTests.swift
- Tests/EventsExporter/Files/FileTests.swift
- Tests/EventsExporter/Helpers/TestsDirectory.swift
- Tests/EventsExporter/Persistence/FileReaderTests.swift
- Tests/EventsExporter/Persistence/FileWriterTests.swift
- Tests/EventsExporter/Persistence/FilesOrchestratorTests.swift
- Tests/EventsExporter/Upload/DataUploadWorkerTests.swift
Swift library ITR catchup: added correlation ID.
Added correlation ID to test metadata.
> [CIVIS-9211] Add Intelligent Test Runner correlation ID

- Sources/DatadogSDKTesting/IntelligentTestRunner/GitUploader.swift
Fallbacks for Git unshallow process if main command failed
Added fallbacks calls as described in documentation
> [CIVIS-3053] added fallbacks for git unshallow

- .github/workflows/createRelease.yml
- .github/workflows/integrationTests.yml
- IntegrationTests/UITests/IntegrationTestsUITests.xctestplan
- Makefile
- Package.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/DDTestObserver.swift
- Sources/DatadogSDKTesting/IntelligentTestRunner/IntelligentTestRunner.swift
- Sources/DatadogSDKTesting/Utils/Log.swift
- Sources/EventsExporter/EventsExporter.swift
- Sources/EventsExporter/IntelligentTestRunner/ITRConfigFormat.swift
- Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
- Sources/EventsExporter/IntelligentTestRunner/SkipTestsFormat.swift
To Reduce overhead on branches where we shouldn't wait for Git upload.
Added handling of 'required_git' option from ITR settings response.
> [CIVIS-8070] added required_git option handling

- DatadogSDKTesting.xcodeproj/project.pbxproj
- IntegrationTests/App/IntegrationTests.swift
- IntegrationTests/UITests/IntegrationTestsRunner.swift
- Makefile
- README.md
- Sources/CDatadogSDKTesting/CodeCoverage.cpp
- Sources/DatadogSDKTesting/Config.swift
- Sources/DatadogSDKTesting/Coverage/DDCoverageHelper.swift
- Sources/DatadogSDKTesting/DDTags.swift
- Sources/DatadogSDKTesting/DDTest.swift
- Sources/DatadogSDKTesting/DDTestModule.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/DDTestObserver.swift
- Sources/DatadogSDKTesting/DDTestSession.swift
- Sources/DatadogSDKTesting/DDTestSuite.swift
- Sources/DatadogSDKTesting/DDTracer.swift
- Sources/DatadogSDKTesting/Endpoint.swift
- Sources/DatadogSDKTesting/Environment/EnvironmentKeys.swift
- Sources/DatadogSDKTesting/FrameworkLoadHandler.swift
- Sources/DatadogSDKTesting/IntelligentTestRunner/ITRSkippabble.swift
- Sources/DatadogSDKTesting/IntelligentTestRunner/SkippedTest.swift
- Sources/DatadogSDKTesting/Utils/Clock.swift
- Sources/EventsExporter/Files/Directory.swift
- Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
- Sources/EventsExporter/Upload/DataUploader.swift
- Sources/EventsExporter/Upload/DatadogEndpoints.swift
- Tests/DatadogSDKTesting/DDTestObserverTests.swift
- Tests/DatadogSDKTesting/DDTracerTests.swift
- Tests/EventsExporter/Utils/SwiftUtilsTests.swift
A lot of fixes for the new release:
* Fixed Code Coverage reporting
* Fixed couple of crashes
* Better ITR skipping
* Better Endpoint handling
* Fixed hang in NTP sync logic
> Fixes before the new release

- .github/workflows/createRelease.yml
- IntegrationTests/UITests/IntegrationTestsRunner.swift
- Makefile
Release scripts don't work properly. Fixed them
GH auth isn't working
> fixes to release scripts

- Makefile
fixed env variable name in Makefile
Updated Makefile
> fixed GH_TOKEN name in the Makefile

- .github/workflows/createRelease.yml
Fixed typo in github action yml file
Replaced tab with spaces
> fixed spaces in the createRelease.yml

- Sources/DatadogSDKTesting/Config.swift
- Sources/DatadogSDKTesting/Coverage/DDCoverageHelper.swift
- Sources/DatadogSDKTesting/DDTracer.swift
- Sources/DatadogSDKTesting/Environment/EnvironmentKeys.swift
- Sources/DatadogSDKTesting/IntelligentTestRunner/SkippedTest.swift
- Sources/EventsExporter/CoverageExporter/CoverageExporter.swift
- Sources/EventsExporter/EventsExporter.swift
- Sources/EventsExporter/ExporterConfiguration.swift
- Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
- Sources/EventsExporter/Logs/LogsExporter.swift
- Sources/EventsExporter/Spans/SpansExporter.swift
- Sources/EventsExporter/Upload/DataUploadWorker.swift
- Sources/EventsExporter/Upload/DatadogEndpoints.swift
- Sources/EventsExporter/Upload/HTTPClient.swift
- Sources/EventsExporter/Utils/Feature.swift
Fixed test suite and module split for Quick tests.
Added network debug mode.
Added one more debug env variable.
> better test name split logic. network debug env variable

- Sources/EventsExporter/Upload/HTTPClient.swift
- Tests/EventsExporter/EventsExporterTests.swift
- Tests/EventsExporter/Helpers/CoreMocks.swift
- Tests/EventsExporter/Logs/LogsExporterTests.swift
- Tests/EventsExporter/Spans/SpansExporterTests.swift
- Tests/EventsExporter/Upload/DataUploadWorkerTests.swift
- Tests/EventsExporter/Upload/DataUploaderTests.swift
- Tests/EventsExporter/Upload/HTTPClientTests.swift
Tests are broken in the EventExporter
Passed debug parameter to the constructor
> fixed EventExporter tests

- DatadogSDKTesting.podspec
- DatadogSDKTesting.xcodeproj/project.pbxproj
- Package.swift
Updated binary for release
Updated checksums
> Updated binary package version to 2.5.0-alpha3

- Sources/DatadogSDKTesting/Config.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/Environment/Environment.swift
Added debug logs for provided config and environment to improve debug.
Added description for environment and config structures. Printed them on start
> added environment and config debug logs

- Sources/DatadogSDKTesting/DDTest.swift
Added a public way to get current test. It can be used for custom tags and other test modification
Added getter for the current test stored property
> added current test static property

- DatadogSDKTesting.xcodeproj/project.pbxproj
Switched OpenTelemetry back from fork to the main repo
Switched  to the commit
> opentelemetry repo change

- Tests/DatadogSDKTesting/Utils/FileLocatorTests.swift
Fixed bug in the test
Recreated temp folder before calling symbolicator
> fixed test for file locator

- Sources/DatadogSDKTesting/IntelligentTestRunner/IntelligentTestRunner.swift
- Sources/EventsExporter/Spans/SpanEncoder.swift
Fixed `itr_correlation_id` field.
Moved field into the test body. Fixed caching of the skipped test request.
> moved correlation id to the body of the test

- Sources/DatadogSDKTesting/Coverage/DDCoverageHelper.swift
Small PR with better logs for ulimit
Added better logs
> better open file limit debug logs

- DatadogSDKTesting.xcodeproj/project.pbxproj
- Sources/DatadogSDKTesting/Config.swift
- Sources/DatadogSDKTesting/Coverage/CoveragePriority.swift
- Sources/DatadogSDKTesting/Coverage/DDCoverageHelper.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/Environment/EnvironmentKeys.swift
Added configuration option to control per-test code coverage queue priority
Added env variable
> added coverage queue priority env variable

- DatadogSDKTesting.podspec
- DatadogSDKTesting.xcodeproj/project.pbxproj
- Package.swift
Updated binary version and hash
By github action
> Updated binary package version to 2.5.1-alpha3

- Sources/DatadogSDKTesting/Config.swift
- Sources/DatadogSDKTesting/Coverage/CoveragePriority.swift
Debug logs for code coverage priority configuration
Added two log strings
> added log for coverage queue priority

- DatadogSDKTesting.xcodeproj/project.pbxproj
- Sources/DatadogSDKTesting/DDTags.swift
- Sources/DatadogSDKTesting/DDTest.swift
- Sources/DatadogSDKTesting/DDTestModule.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/DDTestSuite.swift
- Sources/DatadogSDKTesting/DDTracer.swift
- Sources/DatadogSDKTesting/Environment/Environment.swift
- Sources/DatadogSDKTesting/Utils/PlatformUtils.swift
- Sources/EventsExporter/ExporterConfiguration.swift
- Sources/EventsExporter/Spans/SpanMetadata.swift
- Sources/EventsExporter/Spans/SpansExporter.swift
- Sources/EventsExporter/Utils/EncodableValue.swift
- Tests/EventsExporter/EventsExporterTests.swift
- Tests/EventsExporter/Logs/LogsExporterTests.swift
- Tests/EventsExporter/Spans/SpansExporterTests.swift
Added tag for the CPU count sending
Created new SpanMetadata structure to allow custom tags.
Added cpu count to it
> [SDTEST-873] Send CPU count

- DatadogSDKTesting.podspec
- DatadogSDKTesting.xcodeproj/project.pbxproj
- Package.swift
Binary hashes update for new beta version
By github actions
> Version 2.5.2-beta2

- IntegrationTests/App/IntegrationTests.swift
- IntegrationTests/UITests/IntegrationTestsRunner.swift
Added some flaky test to the integration tests so we can test retries and flake detection
Added random failing test
> Added flaky test to the Integration Tests

- IntegrationTests/App/IntegrationTests.swift
- IntegrationTests/UITests/IntegrationTestsRunner.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
Fixed check for Code Coverage activation
Changed check in the if
> Fixed Code Coverage activation rule

- README.md
README has outdated information and links.
Updated outdated information and links
> [SDTEST-568] updated readme

- DatadogSDKTesting.xcodeproj/project.pbxproj
- Sources/DatadogSDKTesting/DDTags.swift
- Sources/DatadogSDKTesting/DDTracer.swift
- Sources/DatadogSDKTesting/Environment/Span+Environment.swift
- Sources/DatadogSDKTesting/Utils/SDKCapabilities.swift
- Tests/DatadogSDKTesting/EnvironmentTests.swift
Added library capabilities as tags to the metadata
* Added capabilities enum
* Added static variable with current library capablities
* Stored it in metadata
> [SDTEST-1617] added capability tags to the meta

- DatadogSDKTesting.xcodeproj/project.pbxproj
- Sources/DatadogSDKTesting/DDTags.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/DDTestObserver.swift
- Sources/DatadogSDKTesting/DDXCTestCase.swift
- Sources/DatadogSDKTesting/EarlyFlakeDetection.swift
- Sources/DatadogSDKTesting/KnownTests.swift
- Sources/EventsExporter/EventsExporter.swift
- Sources/EventsExporter/KnownTestsService.swift
- Sources/EventsExporter/SettingsService.swift
- Tests/DatadogSDKTesting/EarlyFlakeDetectionTests.swift
New tests are marked with "is_new" tag. Retry reason added for the retries
* Split EFD service to KnownTests and EFD.
* Added KnownTests initialisation.
* Added dependency for KnownTests to EFD initialisation.
* Updated test tagging logic.
> [SDTEST-1276] Implemented Known Tests

- Sources/DatadogSDKTesting/DDTestModule.swift
- Sources/DatadogSDKTesting/DDTestMonitor.swift
- Sources/DatadogSDKTesting/DDTestSession.swift
- Sources/DatadogSDKTesting/TestImpactAnalysis/TestImpactAnalysis.swift
Fixed TIA enablement logic and tags.
Tags added to the module and session.
TIA uses `tests_skipping` setting and can be executed only in the coverage collection mode.
> TIA fixes for the new release

- .github/workflows/createRelease.yml
- Makefile
base64 parameters were wrong in the release script and it failed
Tweaked parameters and script
> Fixed release script

- DatadogSDKTesting.podspec
- DatadogSDKTesting.xcodeproj/project.pbxproj
- Package.swift
Updated hashes for 2.6.0-beta2
By Github Action scropt
> Updated binary package version to 2.6.0-beta2

- Sources/DatadogSDKTesting/AutomaticTestRetries.swift
- Sources/DatadogSDKTesting/DDTags.swift
- Sources/DatadogSDKTesting/DDTestObserver.swift
- Sources/DatadogSDKTesting/EarlyFlakeDetection.swift
- Sources/DatadogSDKTesting/Feature.swift
- Sources/DatadogSDKTesting/RetryAndSkipTags.swift
- Sources/DatadogSDKTesting/TestImpactAnalysis/TestImpactAnalysis.swift
- Sources/DatadogSDKTesting/TestManagement.swift
- Sources/EventsExporter/IntelligentTestRunner/ITRService.swift
- Sources/EventsExporter/IntelligentTestRunner/SkipTestsFormat.swift
- Sources/EventsExporter/Utils/JSONGeneric.swift
- Tests/DatadogSDKTesting/Features/MockTestRunner.swift
- Tests/DatadogSDKTesting/Features/TestImpactAnalysisTests.swift
- Tests/DatadogSDKTesting/Features/TestManagementTests.swift
* Added failure suppression reason tag.
* Added module to the TIA skipped tests.
* Feature adds error suppression reason now.
* Find out that module name is stored inside the `configurations` map of the test.
> [SDTEST-2604] Added failure suppression reason
